id: app
title: Sample Component App
type: project
version: 0.5
icon: app.png
catalog:
  category: Technology
  vendor: GovReady
  vendor_url: http://www.govready.com
  status: Operational
  version: 0.2
  source_url: https://github.com/GovReady/govready-sample-apps/apps/sample_component_app
  description:
    short: |
      This is an example component app for compliance app developers.
    long: |
      This app is intended to be used by developers of GovReady Compliance Apps to learn how to create a compliance app.
  recommended_for:
  - key_short: Org
    value: Small
  - key_short: Tech
    value: Sophisticated
  - key_short: Role
    value: developers
introduction:
  format: markdown
  template: |
    Welcome to the Sample Component App. If you have authoring tools enabled,
    you will be able to edit module questions inside Sample Module.
questions:
- id: module
  title: Sample Module
  type: module
  module-id: module
  icon: app.png
